### ISSUE TITLE
java.lang.IllegalArgumentException: trying to add a signature with an unexpected debtor

### ISSUE THREAD

**Issue by liulinhui** [NEMModules/nem-apps-lib#17]
when i use 'BlockApi.getBlockByHeight()'  to get block 1711952, nothing wrong, but block 1711953, this error happened... , can you help me ???
```
java.lang.IllegalArgumentException: trying to add a signature with an unexpected debtor
	at org.nem.core.model.MultisigTransaction.addSignature(MultisigTransaction.java:82)
	at org.nem.core.model.MultisigTransaction.lambda$new$0(MultisigTransaction.java:50)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.nem.core.model.MultisigTransaction.<init>(MultisigTransaction.java:50)
	at org.nem.core.model.TransactionFactory.deserialize(TransactionFactory.java:72)
	at org.nem.core.model.TransactionFactory.lambda$static$0(TransactionFactory.java:17)
	at org.nem.core.serialization.JsonDeserializer.deserializeObject(JsonDeserializer.java:147)
	at org.nem.core.serialization.JsonDeserializer.readOptionalObjectArray(JsonDeserializer.java:139)
	at org.nem.core.serialization.Deserializer.readObjectArray(Deserializer.java:279)
	at org.nem.core.model.Block.<init>(Block.java:79)

```

**Comment by shenyaqi9527** [comment]
@liulinhui 你是怎么解决这个的，我也遇到了这个问题
